# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src import roguelike_pb2 as src_dot_roguelike__pb2


class GameStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/Game/GetMap',
                request_serializer=src_dot_roguelike__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_roguelike__pb2.Map.FromString,
                )
        self.GetMobs = channel.unary_unary(
                '/Game/GetMobs',
                request_serializer=src_dot_roguelike__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_roguelike__pb2.Mobs.FromString,
                )
        self.GetPlayer = channel.unary_unary(
                '/Game/GetPlayer',
                request_serializer=src_dot_roguelike__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_roguelike__pb2.Player.FromString,
                )
        self.SubscribeToUpdates = channel.unary_stream(
                '/Game/SubscribeToUpdates',
                request_serializer=src_dot_roguelike__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_roguelike__pb2.Empty.FromString,
                )
        self.SendIntention = channel.unary_unary(
                '/Game/SendIntention',
                request_serializer=src_dot_roguelike__pb2.Intention.SerializeToString,
                response_deserializer=src_dot_roguelike__pb2.Empty.FromString,
                )


class GameServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMobs(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayer(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToUpdates(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendIntention(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=src_dot_roguelike__pb2.Empty.FromString,
                    response_serializer=src_dot_roguelike__pb2.Map.SerializeToString,
            ),
            'GetMobs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMobs,
                    request_deserializer=src_dot_roguelike__pb2.Empty.FromString,
                    response_serializer=src_dot_roguelike__pb2.Mobs.SerializeToString,
            ),
            'GetPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayer,
                    request_deserializer=src_dot_roguelike__pb2.Empty.FromString,
                    response_serializer=src_dot_roguelike__pb2.Player.SerializeToString,
            ),
            'SubscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUpdates,
                    request_deserializer=src_dot_roguelike__pb2.Empty.FromString,
                    response_serializer=src_dot_roguelike__pb2.Empty.SerializeToString,
            ),
            'SendIntention': grpc.unary_unary_rpc_method_handler(
                    servicer.SendIntention,
                    request_deserializer=src_dot_roguelike__pb2.Intention.FromString,
                    response_serializer=src_dot_roguelike__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Game/GetMap',
            src_dot_roguelike__pb2.Empty.SerializeToString,
            src_dot_roguelike__pb2.Map.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Game/GetMobs',
            src_dot_roguelike__pb2.Empty.SerializeToString,
            src_dot_roguelike__pb2.Mobs.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Game/GetPlayer',
            src_dot_roguelike__pb2.Empty.SerializeToString,
            src_dot_roguelike__pb2.Player.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Game/SubscribeToUpdates',
            src_dot_roguelike__pb2.Empty.SerializeToString,
            src_dot_roguelike__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendIntention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Game/SendIntention',
            src_dot_roguelike__pb2.Intention.SerializeToString,
            src_dot_roguelike__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
